# Setup
title: 对方正在输入
description: 当你觉得自己又丑又穷的时候，不要悲伤，至少你的判断还是对的。
url: https://agajasme.github.io
avatar: /image/img_avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /image/img_bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/

# Optimize Jekyl SEO Tag
twitter:
  username: agajasme
  card: summary
logo: logo.png
social:
  name: 对方正在输入
  links:
    - https://twitter.com/agajasme
    - https://github.com/agajasme
lang: en

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: 对方正在输入
  url: https://github.com/agajasme/
  email: agajasme@gmail.com
